apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
    project: fluxcd-demo
  namespace: fluxcd-demo
spec:
  selector:
    matchLabels:
      app: app2
      project: fluxcd-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: app2
        project: fluxcd-demo
    spec:
      containers:
      - name: app2
        image: docker.io/anvesh35/fluxcd-demo-app2:v4.0.0 # {"$imagepolicy": "fluxcd-demo:app2"}
        ports:
        - containerPort: 80
