apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-controller-rolebinding
subjects:
- kind: ServiceAccount
  name: custom-controller-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: custom-controller-role
  apiGroup: rbac.authorization.k8s.io
